#+TITLE: Posts
#+AUTHOR: Shuvrojit Biswas

#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: ./stories/
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

* First Story                                                         :@story:
:PROPERTIES:
:EXPORT_FILE_NAME: first-story
:EXPORT_DATE: 2023-01-17
:EXPORT_HUGO_MENU: :menu "main"
:EXPORT_CUSTOM_FRONT_MATTER: :draft false :cedric yes
:END:

** There are no people around here.

Pellentesque dapibus suscipit ligula.  Donec posuere augue in quam.  Etiam vel tortor sodales tellus ultricies commodo.  Suspendisse potenti.  Aenean in sem ac leo mollis blandit.  Donec neque quam, dignissim in, mollis nec, sagittis eu, wisi.  Phasellus lacus.  Etiam laoreet quam sed arcu.  Phasellus at dui in ligula mollis ultricies.  Integer placerat tristique nisl.  Praesent augue.  Fusce commodo.  Vestibulum convallis, lorem a tempus semper, dui dui euismod elit, vitae placerat urna tortor vitae lacus.  Nullam libero mauris, consequat quis, varius et, dictum id, arcu.  Mauris mollis tincidunt felis.  Aliquam feugiat tellus ut neque.  Nulla facilisis, risus a rhoncus fermentum, tellus tellus lacinia purus, et dictum nunc justo sit amet elit.
